apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "backup.cloudinfra.be/v1alpha1",
          "kind": "KopiaBackup",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "kopia-operator"
            },
            "name": "kopiabackup-sample"
          },
          "spec": {
            "pvcName": "my-app-data",
            "repositoryName": "kopiarepository-sample",
            "schedule": "0 3 * * *",
            "suspend": false
          }
        },
        {
          "apiVersion": "backup.cloudinfra.be/v1alpha1",
          "kind": "KopiaRepository",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "kopia-operator"
            },
            "name": "kopiasftprepository-sample",
            "namespace": "default"
          },
          "spec": {
            "defaultSchedule": "0 2 * * *",
            "hostname": "cluster",
            "passwordSecretName": "kopia-repository-password",
            "sftpOptions": {
              "credentialsSecret": "kopia-sftp-credentials",
              "host": "sftp.example.com",
              "path": "/backups/kopia-repo",
              "port": 22
            },
            "storageType": "sftp",
            "username": "kopia"
          }
        },
        {
          "apiVersion": "backup.cloudinfra.be/v1alpha1",
          "kind": "KopiaRepository",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "kopia-operator"
            },
            "name": "kopiarepository-sample"
          },
          "spec": {
            "defaultSchedule": "0 2 * * *",
            "fileSystemOptions": {
              "nfsPath": "/export/backup",
              "nfsServer": "10.0.0.1",
              "path": "/backup/kopia"
            },
            "hostname": "cluster",
            "passwordSecretName": "kopia-repository-password",
            "storageType": "filesystem",
            "username": "kopia"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2026-04-10T19:11:48Z"
    operators.operatorframework.io/builder: operator-sdk-v1.39.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: kopia-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: KopiaBackup is the Schema for the kopiabackups API.
      displayName: Kopia Backup
      kind: KopiaBackup
      name: kopiabackups.backup.cloudinfra.be
      version: v1alpha1
    - description: KopiaRepository is the Schema for the kopiarepositories API.
      displayName: Kopia Repository
      kind: KopiaRepository
      name: kopiarepositories.backup.cloudinfra.be
      version: v1alpha1
  description: A Kubernetes operator for managing [Kopia](https://kopia.io/) backup
    operations for Persistent Volume Claims (PVCs).
  displayName: kopia-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - pods/exec
          verbs:
          - create
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - backup.cloudinfra.be
          resources:
          - kopiabackups
          - kopiarepositories
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - backup.cloudinfra.be
          resources:
          - kopiabackups/finalizers
          - kopiarepositories/finalizers
          verbs:
          - update
        - apiGroups:
          - backup.cloudinfra.be
          resources:
          - kopiabackups/status
          - kopiarepositories/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - batch
          resources:
          - cronjobs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: kopia-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: kopia-operator
          control-plane: controller-manager
        name: kopia-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: registry.k8s.io/kubebuilder/kube-rbac-proxy:v0.16.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: controller:latest
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: kopia-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: kopia-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - backup
  - kopia
  links:
  - name: Kopia Operator
    url: https://kopia-operator.domain
  maintainers:
  - email: git@bernardi.be
    name: fastlorenzo
  maturity: alpha
  provider:
    name: fastlorenzo
    url: https://github.com/fastlorenzo/kopia-operator
  version: 0.0.1
