//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupHistoryEntry) DeepCopyInto(out *BackupHistoryEntry) {
	*out = *in
	in.StartTime.DeepCopyInto(&out.StartTime)
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupHistoryEntry.
func (in *BackupHistoryEntry) DeepCopy() *BackupHistoryEntry {
	if in == nil {
		return nil
	}
	out := new(BackupHistoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopiaBackup) DeepCopyInto(out *KopiaBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopiaBackup.
func (in *KopiaBackup) DeepCopy() *KopiaBackup {
	if in == nil {
		return nil
	}
	out := new(KopiaBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KopiaBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopiaBackupCustomValidator) DeepCopyInto(out *KopiaBackupCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopiaBackupCustomValidator.
func (in *KopiaBackupCustomValidator) DeepCopy() *KopiaBackupCustomValidator {
	if in == nil {
		return nil
	}
	out := new(KopiaBackupCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopiaBackupList) DeepCopyInto(out *KopiaBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KopiaBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopiaBackupList.
func (in *KopiaBackupList) DeepCopy() *KopiaBackupList {
	if in == nil {
		return nil
	}
	out := new(KopiaBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KopiaBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopiaBackupSpec) DeepCopyInto(out *KopiaBackupSpec) {
	*out = *in
	if in.SuccessfulJobsHistoryLimit != nil {
		in, out := &in.SuccessfulJobsHistoryLimit, &out.SuccessfulJobsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.FailedJobsHistoryLimit != nil {
		in, out := &in.FailedJobsHistoryLimit, &out.FailedJobsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
	if in.ActiveDeadlineSeconds != nil {
		in, out := &in.ActiveDeadlineSeconds, &out.ActiveDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	if in.BackoffLimit != nil {
		in, out := &in.BackoffLimit, &out.BackoffLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopiaBackupSpec.
func (in *KopiaBackupSpec) DeepCopy() *KopiaBackupSpec {
	if in == nil {
		return nil
	}
	out := new(KopiaBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopiaBackupStatus) DeepCopyInto(out *KopiaBackupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastBackupTime != nil {
		in, out := &in.LastBackupTime, &out.LastBackupTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulBackupTime != nil {
		in, out := &in.LastSuccessfulBackupTime, &out.LastSuccessfulBackupTime
		*out = (*in).DeepCopy()
	}
	if in.BackupHistory != nil {
		in, out := &in.BackupHistory, &out.BackupHistory
		*out = make([]BackupHistoryEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopiaBackupStatus.
func (in *KopiaBackupStatus) DeepCopy() *KopiaBackupStatus {
	if in == nil {
		return nil
	}
	out := new(KopiaBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopiaRepository) DeepCopyInto(out *KopiaRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopiaRepository.
func (in *KopiaRepository) DeepCopy() *KopiaRepository {
	if in == nil {
		return nil
	}
	out := new(KopiaRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KopiaRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopiaRepositoryCachingSpec) DeepCopyInto(out *KopiaRepositoryCachingSpec) {
	*out = *in
	out.ContentCacheSize = in.ContentCacheSize.DeepCopy()
	out.ContentCacheSizeLimit = in.ContentCacheSizeLimit.DeepCopy()
	out.MetadataCacheSize = in.MetadataCacheSize.DeepCopy()
	out.MetadataCacheSizeLimit = in.MetadataCacheSizeLimit.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopiaRepositoryCachingSpec.
func (in *KopiaRepositoryCachingSpec) DeepCopy() *KopiaRepositoryCachingSpec {
	if in == nil {
		return nil
	}
	out := new(KopiaRepositoryCachingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopiaRepositoryCustomValidator) DeepCopyInto(out *KopiaRepositoryCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopiaRepositoryCustomValidator.
func (in *KopiaRepositoryCustomValidator) DeepCopy() *KopiaRepositoryCustomValidator {
	if in == nil {
		return nil
	}
	out := new(KopiaRepositoryCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopiaRepositoryList) DeepCopyInto(out *KopiaRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KopiaRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopiaRepositoryList.
func (in *KopiaRepositoryList) DeepCopy() *KopiaRepositoryList {
	if in == nil {
		return nil
	}
	out := new(KopiaRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KopiaRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopiaRepositorySpec) DeepCopyInto(out *KopiaRepositorySpec) {
	*out = *in
	in.Caching.DeepCopyInto(&out.Caching)
	out.FileSystemOptions = in.FileSystemOptions
	in.SFTPOptions.DeepCopyInto(&out.SFTPOptions)
	in.Server.DeepCopyInto(&out.Server)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopiaRepositorySpec.
func (in *KopiaRepositorySpec) DeepCopy() *KopiaRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(KopiaRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopiaRepositoryStatus) DeepCopyInto(out *KopiaRepositoryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopiaRepositoryStatus.
func (in *KopiaRepositoryStatus) DeepCopy() *KopiaRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(KopiaRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopiaRepositoryStorageFileSystemSpec) DeepCopyInto(out *KopiaRepositoryStorageFileSystemSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopiaRepositoryStorageFileSystemSpec.
func (in *KopiaRepositoryStorageFileSystemSpec) DeepCopy() *KopiaRepositoryStorageFileSystemSpec {
	if in == nil {
		return nil
	}
	out := new(KopiaRepositoryStorageFileSystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopiaRepositoryStorageSFTPSpec) DeepCopyInto(out *KopiaRepositoryStorageSFTPSpec) {
	*out = *in
	if in.DirShards != nil {
		in, out := &in.DirShards, &out.DirShards
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopiaRepositoryStorageSFTPSpec.
func (in *KopiaRepositoryStorageSFTPSpec) DeepCopy() *KopiaRepositoryStorageSFTPSpec {
	if in == nil {
		return nil
	}
	out := new(KopiaRepositoryStorageSFTPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopiaServerExposureSpec) DeepCopyInto(out *KopiaServerExposureSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopiaServerExposureSpec.
func (in *KopiaServerExposureSpec) DeepCopy() *KopiaServerExposureSpec {
	if in == nil {
		return nil
	}
	out := new(KopiaServerExposureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopiaServerSpec) DeepCopyInto(out *KopiaServerSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	in.TLS.DeepCopyInto(&out.TLS)
	out.Exposure = in.Exposure
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopiaServerSpec.
func (in *KopiaServerSpec) DeepCopy() *KopiaServerSpec {
	if in == nil {
		return nil
	}
	out := new(KopiaServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopiaServerTLSSpec) DeepCopyInto(out *KopiaServerTLSSpec) {
	*out = *in
	if in.CertificateDNSNames != nil {
		in, out := &in.CertificateDNSNames, &out.CertificateDNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopiaServerTLSSpec.
func (in *KopiaServerTLSSpec) DeepCopy() *KopiaServerTLSSpec {
	if in == nil {
		return nil
	}
	out := new(KopiaServerTLSSpec)
	in.DeepCopyInto(out)
	return out
}
