# permissions for end users to view kopiarepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kopia-operator
    app.kubernetes.io/managed-by: kustomize
  name: kopiarepository-viewer-role
rules:
  - apiGroups:
      - backup.cloudinfra.be
    resources:
      - kopiarepositories
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - backup.cloudinfra.be
    resources:
      - kopiarepositories/status
    verbs:
      - get
