# permissions for end users to view kopiabackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kopia-operator
    app.kubernetes.io/managed-by: kustomize
  name: kopiabackup-viewer-role
rules:
- apiGroups:
  - backup.cloudinfra.be
  resources:
  - kopiabackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.cloudinfra.be
  resources:
  - kopiabackups/status
  verbs:
  - get
