---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - backup.cloudinfra.be
  resources:
  - kopiabackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.cloudinfra.be
  resources:
  - kopiabackups/finalizers
  verbs:
  - update
- apiGroups:
  - backup.cloudinfra.be
  resources:
  - kopiabackups/status
  verbs:
  - get
  - patch
  - update
