apiVersion: backup.cloudinfra.be/v1alpha1
kind: KopiaBackup
metadata:
  labels:
    app.kubernetes.io/name: kopia-operator
    app.kubernetes.io/managed-by: kustomize
  name: kopiabackup-sample
spec:
  pvcName: my-app-data
  schedule: "0 3 * * *"
  repository: my-repository
  suspend: false
