# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - bases/backup.cloudinfra.be_kopiabackups.yaml
  - bases/backup.cloudinfra.be_kopiarepositories.yaml
# patches:
# Uncomment the following to enable webhook conversion for each CRD
# - path: patches/webhook_in_kopiabackups.yaml
# - path: patches/webhook_in_kopiarepositories.yaml

# Uncomment the following to enable cert-manager CA injection for each CRD
# - path: patches/cainjection_in_kopiabackups.yaml
# - path: patches/cainjection_in_kopiarepositories.yaml

# configurations:
# - kustomizeconfig.yaml
